### ISSUE TITLE
Custom deployment issue

### ISSUE THREAD

**Issue by ozanoguz** [jvhoof/fortinet-azure-solutions#262]
When I try both "Deploy to Azure" options it's giving following error:

There was an error downloading the template from URI 'https://raw.githubusercontent.com/40net-cloud/fortinet-azure-solutions/fwb-an-license/FortiWeb/Active-Active/mainTemplate.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. 
There was an error downloading from URI 'https://raw.githubusercontent.com/40net-cloud/fortinet-azure-solutions/fwb-an-license/FortiWeb/Active-Active/createUiDefinition.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint.

**Comment by jvhoof** [comment]
Fixed both. They where linked to a branch.
