### ISSUE TITLE
Incorrect BGP Peer IP Addresses?

### ISSUE THREAD

**Issue by tco-bfisk** [jvhoof/fortinet-azure-solutions#277]
I noticed that during the creation of the Route Server peers (pointing to the fortigates) .69 and .70 are the peers created however shouldn't this be the internal IPs of the two fortigates which are .68 and .69?

Thank you!

**Comment by jvhoof** [comment]
Hi,

This should be the internal IP addresses (port2) of the FortiGate. Which template did you try to deploy?

https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate/AzureRouteServer/Active-Passive

I've tried to deploy this template today and the configuration is correct. The azuredeploy.json also refers to the correct IP addresses. 

I'm looking at the same issue here or is there someething else wrong I'm missing. Happy to hear your side.

    {
      "type": "Microsoft.Network/virtualHubs/bgpConnections",
      "apiVersion": "2020-06-01",
      "name": "[concat(variables('fgRouteServerName'), '/', variables('fgaRouteServerBGP'))]",
      "location": "[parameters('location')]",
      "dependsOn": [
        "[resourceId('Microsoft.Network/virtualHubs/ipConfigurations', variables('fgRouteServerName'), variables('fgRouteServerIPConfig'))]"
      ],
      "properties": {
        "peerAsn": "[parameters('fortiGateBGPASN')]",
        "peerIp": "[variables('**sn2IPfga**')]"
      }
    },
    {
      "type": "Microsoft.Network/virtualHubs/bgpConnections",
      "apiVersion": "2020-06-01",
      "name": "[concat(variables('fgRouteServerName'), '/', variables('fgbRouteServerBGP'))]",
      "dependsOn": [
        "[resourceId('Microsoft.Network/virtualHubs/ipConfigurations', variables('fgRouteServerName'), variables('fgRouteServerIPConfig'))]",
        "[resourceId('Microsoft.Network/virtualHubs/bgpConnections', variables('fgRouteServerName'), variables('fgaRouteServerBGP'))]"
      ],
      "properties": {
        "peerAsn": "[parameters('fortiGateBGPASN')]",
        "peerIp": "[variables('**sn2IPfgb**')]"
      }
    },

Regards,

joeri
