### ISSUE TITLE
Unable to access FortiGate site after deploying GWLB BYOD template.

### ISSUE THREAD

**Issue by rmurakami118** [jvhoof/fortinet-azure-solutions#322]
I deployed FortiGate to Azure from the site below.

FortiGate Next-Generation Firewall in Azure GWLB
https://github.com/fortinetsolutions/Azure-Templates/tree/master/GWLB

When deploying, if I select "fortinet_fg-vm_payg_20190624" for the "Forti Gate Image SKU", I can access the FortiGate site,
but if I select "fortinet_fg-vm", I will not be able to access the FortiGate site.

How can BYOD use FortiGate?

**Comment by jvhoof** [comment]
Hi,

Please use the official template from the Fortinet repository:
https://github.com/fortinet/azure-templates/tree/main/FortiGate/AzureGatewayLoadBalancer
or our early release repo here:
https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate/AzureGatewayLoadBalancer

In these templates, you can select BYOL or PAYG.

Hope this helps you in your deployment.

Joeri

**Comment by rmurakami118** [comment]
Hi Joeri-san,

Thank you for reply.
I have used the official template to deploy.
The deployment was successful, but the FortiGate site was still inaccessible
https://github.com/fortinet/azure-templates/tree/main/FortiGate/AzureGatewayLoadBalancer

I have summarized the situation in the attached excel.
Could you please confirm?

Best Regards.

ALSI Murakami

**Comment by rmurakami118** [comment]
Hi Joeri-san,

I'm sorry, I couldn't attach the file.
I will attach it again.
Could you please confirm?

Murakami
[FortiGate_error_20230808.xlsx](https://github.com/40net-cloud/fortinet-azure-solutions/files/12365590/FortiGate_error_20230808.xlsx)

**Comment by jvhoof** [comment]
Hi Murakami-San,

I've reviewed your submitted errors in the xlsx file. There seems to be an issue with FortiOS version 7.4.0 on the routing it seems combined with our config we supply in the template. This is however not the default FortiOS version we currently recommend. 

Can you try again with version 7.2.5? That should work accordingly. Alternatively you can remove the static route number 2. 

Let us know how it goes.

Joeri

**Comment by rmurakami118** [comment]
Hi Joeri-san,

Thank you for youre reply.
I tried version 7.2.5 and I can access the site both PAYG and BYOL.
Thank you very much !

Best Regards.

Murakami.
