### ISSUE TITLE
default nva sku in terraform script does not work

### ISSUE THREAD

**Issue by yagosys** [jvhoof/fortinet-azure-solutions#366]
Have to change it to "fortigate_vwan_nva" to make it work.
the default vaule is "'fortinet-sdwan-and-ngfw' or 'fortinet-ngfw'.   but it does not work.

fortinet-azure-solutions/FortiGate/AzureVirtualWAN/terraform/varible.tf

variable "fgt_sku" {
  default = "fortigate_vwan_nva"
}

**Comment by jvhoof** [comment]
Thanks for reporting this. We will check this and update the template where needed.

Joeri

**Comment by jvhoof** [comment]
Updated modules have been posted on the below link which contains other FortiGate Terraform modules as well: 
https://github.com/40net-cloud/terraform-azure-fortigate
